/** @type {import('prettier').Config} */
module.exports = {
  endOfLine: "auto",
  trailingComma: "none",
  printWidth: 100,
  tabWidth: 2,
  importOrderTypeScriptVersion: "5.3.3",
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  plugins: [
    "@ianvs/prettier-plugin-sort-imports",
    "prettier-plugin-organize-imports",
    "prettier-plugin-tailwindcss"
  ],
  importOrder: [
    "",
    "<TYPES>",
    "<TYPES>^[.]",
    "^types$",
    "^@/types/(.*)$",
    "",
    ".css$",
    ".scss$",
    ".sass$",
    ".less$",
    "",
    "@/styles/(.*)$",
    "@/styles$",
    "",
    "^(react/(.*)$)|^(react$)",
    "^(next/(.*)$)|^(next$)",
    "<BUILTIN_MODULES>",
    "<THIRD_PARTY_MODULES>",
    "",
    "@/app/(.*)$",
    "@/app$",
    "",
    "@/components/(.*)$",
    "@/components$",
    "",
    "@/contexts/(.*)$",
    "@/contexts$",
    "",
    "@/hooks/(.*)$",
    "@/hooks$",
    "",
    "@/libs/(.*)$",
    "@/libs$",
    "",
    "@/services/(.*)$",
    "@/services$",
    "",
    "@/web3/(.*)$",
    "@/web3$",
    "",
    "@/stores/(.*)$",
    "@/stores$",
    "",
    "@/configs/(.*)$",
    "@/configs$",
    "",
    "@/themes/(.*)$",
    "@/themes$",
    "",
    "@/content/(.*)$",
    "@/content$",
    "",
    "^[./]"
  ]
};
