export enum LivestreamEvents {
    StreamData = 'streamData',
    StartStream = 'stream.start',
    EndStream = 'stream.end',
    JoinStream = 'stream.join',
    LeaveStream = 'stream.left',
    SendMessage = 'stream.message',
    LikeStream = 'stream.like',
    ViewCountUpdate = 'stream.viewers.update',
    StreamPaused = 'stream.paused',
    StreamResumed = 'stream.resumed',
    UserBanned = 'stream.user.banned',
    UserMuted = 'stream.user.muted',
    StreamError = 'stream.error',
}